cache:
  - file: backend/package-lock.json
    path: backend/node_modules
  - file: frontend/yarn.lock
    path: frontend/node_modules
setup:
  commands:
    - cp seed.js /docker-entrypoint-initdb.d/
services:
  frontend:
    runtime: node
    port: 3000
    path: frontend
    build:
      - npm install react-scripts@3.4.1 -g --silent
      - yarn install
      - yarn build
    serve:
      - npx serve build/ -l 3000
  backend:
    runtime: node
    port: 5000
    path: backend
    build:
      - npm install
    serve:
      - node app.js
  mongo:
    image: mongo
    port: 27017
    do-not-expose: true
